### ISSUE TITLE
Project description references "Testacular"

### ISSUE THREAD

**Issue by johnzeringue** [karma-runner/karma-safari-launcher#13]
Currently the GitHub project description reads

    A Testacular plugin. Launcher for Safari.

However, as I understand it, "Testacular" is an old name for Karma. Therefore, in order to be accurate and consistent with the other launcher plugins, I think it should read

    A Karma plugin. Launcher for Safari.

Can someone with appropriate permissions address this when they find time?

**Comment by dignifiedquire** [comment]
Done, thanks for letting me know
