### ISSUE TITLE
No test-execution on Windows

### ISSUE THREAD

**Issue by sbradl** [karma-runner/karma-safari-launcher#5]
I get the following message when I try to use the safari launcher:

WARN [launcher]: Safari have not captured in 60000 ms, killing.

Safari starts and loads the karma page but it does not execute the tests.
I am running Windows 7 Pro 64bit, and Karma 0.10.1

**Comment by Dignifiedquire** [comment]
Safari is not supported under windows anymore, so closing this for now

**Comment by jdmarshall** [comment]
Can we remove this support from the launcher?
